### ISSUE TITLE
404 / missing EmberData API docs of old releases

### ISSUE THREAD

**Issue by bastimeyer** [ember-learn/ember-api-docs#847]
When trying to find old documentation for Ember-Data, error 404 gets returned.

There appear to be two separate issues:

1. The latest docs seem to have a "new" start page for an overview of the ED API docs, and when trying to switch the version from that start page to a version where that page doesn't exist, this will lead to a 404
   - https://api.emberjs.com/ember-data/4.7/modules/ember-data-overview
   - https://api.emberjs.com/ember-data/4.6/modules/ember-data-overview
2. Anything below 3.11 doesn't seem to be available at all anymore, which is pretty bad.
   - https://api.emberjs.com/ember-data/3.11/classes/Model
   - https://api.emberjs.com/ember-data/3.10/classes/Model

**Comment by jenweber** [comment]
Thanks for reporting! I see the same issues as you. I’ll bring this up with the team for troubleshooting ASAP.

**Comment by jedateach** [comment]
@jenweber Yes, please.

**Comment by williamhector** [comment]
@jenweber Is this being resolved?
https://api.emberjs.com/ember/2.18/classes/Component hits a 404 but 
https://api.emberjs.com/ember/2.17/classes/Component works fine.

**Comment by jenweber** [comment]
The original issue reported by @bastimeyer has been resolved via   bugfix for a github URL issue, and version switching 404s are intended behavior (see note below).

@williamhector thanks for dropping by to report the problems with these other links. The issue you pointed out is separate from bastimeyer's links, but does seem to be a real problem! I'll look today. In general, we highly prioritize maintaining and fixing active LTS versions on up. However as the last release of v2, I'd like to see 2.18 docs working ok to aid people in upgrades.

Note: when documentation URLs change between versions due to changes in source code documentation and file structure, trying to switch between those versions will cause a 404. This is expected behavior. We do not create redirects between versions. The best way to get to the docs for a specific version is through navigating to a specific version and using the search/sidebar, instead of locating the docs on a different version and then trying to version switch. However, if a page is broken even from the link in the sidebar, that is indeed a real bug and not intended behavior.

**Comment by jenweber** [comment]
Also if anyone wants to follow along on the more meta effort to fix API docs issues in general, see https://github.com/ember-learn/ember-api-docs/pull/815 which is a work-in-progress, but definitely making good progress!

**Comment by EWhite613** [comment]
Looks all of 3.x has this issue now @jenweber . 3.16 and 3.28.

This breakage seems to be new for those, as was looking at them a week ago with no issue

**Comment by bastimeyer** [comment]
That did not fix this.

Still 404:
- https://api.emberjs.com/ember-data/2.18/classes/DS.Model
- https://api.emberjs.com/ember-data/3.7/classes/DS.Model

And 3.11 is now also 404, compared to what I've posted in the OP:
- https://api.emberjs.com/ember-data/3.11/classes/Model

**Comment by mansona** [comment]
once https://github.com/ember-learn/ember-api-docs-data/pull/16 is merged it will fix **everything** on ember-data 🎉
